---
- name: create data directory
  file:
    path="{{ postgresql_data_directory }}"
    owner=postgres
    group=postgres
    mode=0700
    state=directory

- name: drop previous cluster
  shell: pg_dropcluster --stop 9.4 main

- name: create new cluster
  shell: pg_createcluster --start 9.4 main -d {{ postgresql_data_directory }}
