---
ssl_certificate_name: "ssl_certificate.crt"
ssl_private_key_name: "ssl_private_key.key"

ssl_certificate_path: "/etc/ssl/certs/{{ ssl_certificate_name }}"
ssl_private_key_path: "/etc/ssl/private/{{ ssl_private_key_name }}"
